### ISSUE TITLE
分页一小问题 && thumb 无效

### ISSUE THREAD

**Issue by yuangezhizao** [chakhsu/pinghsu#11]
1. rt，我好像遇到了很奇葩的 bug，为什么 5 块就分页了而不是 6 块？
![20170406170018](https://cloud.githubusercontent.com/assets/16861681/24746190/c8565cfa-1aea-11e7-88aa-ffce0cbd96cb.jpg)
2. rt，自定义`thumb`字段，最新的两篇文章为啥没生效……
![20170406170447](https://cloud.githubusercontent.com/assets/16861681/24746290/29bfa898-1aeb-11e7-89bf-22d37f6ce9c8.jpg)
地址：http://gcy.pe.hu
如能解决，不胜感激！

**Comment by chakhsu** [comment]
分页设置，到后台设置-文章那修改即可；
你试一下用Typecho开发版~ 没遇到这种情况~

**Comment by yuangezhizao** [comment]
问题 1 ：解决；
问题 2 ：我一直用的稳定版，奇怪的是前几个`thumb`都好使，最近的就不好使了……

**Comment by chakhsu** [comment]
问题2的情况可能是因为稳定版的问题，稳定版有很多漏洞，你还是用开发版吧，更省心~

**Comment by yuangezhizao** [comment]
稳定版有漏洞？！表示被吓到了……
感谢提醒！
