### ISSUE TITLE
一个细节问题

### ISSUE THREAD

**Issue by windowsair** [chakhsu/pinghsu#12]
当点击文章目录树中处于当前视图以上的链接时，顶部的导航栏会自动遮住该链接字样。
![2017-04-08_001601](https://cloud.githubusercontent.com/assets/17078589/24808873/2bc0f150-1bf0-11e7-8ee3-55e1c69b86ec.png)

**Comment by chakhsu** [comment]
这个也没办法的，确实是这样的~

**Comment by windowsair** [comment]
😂强迫症表示看了不舒服

**Comment by windowsair** [comment]
@chakhsu 貌似修改锚点位置就可以。http://www.tuicool.com/articles/fuaeq27
