### ISSUE TITLE
如何进入系统后台

### ISSUE THREAD

**Issue by wangwill** [chakhsu/pinghsu#17]
启用大佬的主题后 没有进入后台的接口？

刚启用的时候 在文章评论区还可以看到管理员已登陆以及进入后台。

关闭网页。 之后再开博客便找不到登陆选项了。

**Comment by wangwill** [comment]
问题解决。。。     网址后加/admin/login.php

有考虑在模板某个部分加相关进入后台语句么？

**Comment by chakhsu** [comment]
没，你多玩一段时间就明白的。

**Comment by Xuyiyang23333** [comment]
> 
> 
> 问题解决。。。 网址后加/admin/login.php
> 
> 有考虑在模板某个部分加相关进入后台语句么？

关键是没必要……
