### ISSUE TITLE
Linux命令行代码高亮问题

### ISSUE THREAD

**Issue by Nobiel** [chakhsu/pinghsu#18]
请问Shell Session应该用bash还是shell呢？
感觉应该用\```bash，\```shell不起作用？
另外好像并没有高亮多少关键词啊。

**Comment by chakhsu** [comment]
你看一下官方文档 ，默认的那些就是了。https://highlightjs.org/static/demo/ 
至于高亮的css用的是Xcode，你可以改成你想要的风格。
