### ISSUE TITLE
手机端页面右上角展开之后无法点击`X`关闭

### ISSUE THREAD

**Issue by S8Cloud** [chakhsu/pinghsu#22]
PC 端貌似是通过鼠标指针移动的方式来展开、关闭的，手机端只能点开不能关闭，不知道是故意为之还是 bug。

![image](https://user-images.githubusercontent.com/27051990/31340956-7c30f888-accd-11e7-80a1-7a820eb57f17.png)

**Comment by chakhsu** [comment]
移动端点击事件是touch事件 pc端则是click事件，菜单部分是纯css实现模仿click事件，部分移动端支持。
