### ISSUE TITLE
与lets ssl证书兼容问题

### ISSUE THREAD

**Issue by nickhoo555** [chakhsu/pinghsu#23]
网站迁移，新环境下，仅此主题的博客，一旦恢复主题，https就失效。
环境Ubuntu16，lnmp 部署

**Comment by devzhi** [comment]
我并没有出现这个问题
centos7  lnmp.org1.4  www.sstype.com

**Comment by nickhoo555** [comment]
更新~放着没动，昨天重启了服务器，意外地发现这个问题已经没有了，遇到同样问题的小伙伴可以试着重启一下。
