### ISSUE TITLE
识别不出来

### ISSUE THREAD

**Issue by ideago** [chakhsu/pinghsu#4]
为啥放到themes目录下识别不出来呢，其它主题能正常识别……😓

**Comment by windowsair** [comment]
你的目录权限是否设置正确？

**Comment by chakhsu** [comment]
新建文件夹，重命名为pinghsu，将代码放到这个文件夹内，然后上传这个文件夹到你的themes目录。

**Comment by ideago** [comment]
hello，问题已经解决了，是我自己的问题，我的typecho源码用的也是git管理，你的主题是我直接git下来的，所以我的git提交时一直没有把你的主题提交上去，你那个主题做的很赞呢，赞一个……👍
