### ISSUE TITLE
代码高亮失效

### ISSUE THREAD

**Issue by tom-kst** [chakhsu/pinghsu#58]
大佬好！昨天下载了主题，刚启用时代码高亮正常，但当我添加了后台登陆入口和XQUserAgent插件引用后就失效了，是不是冲突了？
![image](https://github.com/chakhsu/pinghsu/assets/43116646/e79ea10c-5b01-4533-b6dd-133b5cda170c)
![image](https://github.com/chakhsu/pinghsu/assets/43116646/62a550b6-15fe-434e-aeb9-be88df5580c2)
![image](https://github.com/chakhsu/pinghsu/assets/43116646/45af8b6b-2579-49d6-8db5-865181173b35)

**Comment by tom-kst** [comment]
试过删掉这些后加的，也没法恢复高亮

**Comment by chakhsu** [comment]
试一下最新版，刚刚更新了，跟我博客代码同步了。

**Comment by chakhsu** [comment]
> 大佬好！昨天下载了主题，刚启用时代码高亮正常，但当我添加了后台登陆入口和XQUserAgent插件引用后就失效了，是不是冲突了？ ![image](https://private-user-images.githubusercontent.com/43116646/301376696-e79ea10c-5b01-4533-b6dd-133b5cda170c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzQ3MDIsIm5iZiI6MTcwNjgzNDQwMiwicGF0aCI6Ii80MzExNjY0Ni8zMDEzNzY2OTYtZTc5ZWExMGMtNWIwMS00NTMzLWI2ZGQtMTMzYjVjZGExNzBjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwMDQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmEwOWE5YWFhOWI2MWM4NGUwYzhlNjc5YmM0NDZiMTczYWQ4M2VmMDZhODFmYjAwYTcwZGQyNGRjODdlMzM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oTlMHxRK6sS_DMK0lr-4tTVuXjhyZVQAN4x11l2sfjU) ![image](https://private-user-images.githubusercontent.com/43116646/301376746-62a550b6-15fe-434e-aeb9-be88df5580c2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzQ3MDIsIm5iZiI6MTcwNjgzNDQwMiwicGF0aCI6Ii80MzExNjY0Ni8zMDEzNzY3NDYtNjJhNTUwYjYtMTVmZS00MzRlLWFlYjktYmU4OGRmNTU4MGMyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwMDQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzljMWJkMDlmMTdkMzM0YWMwNjZiNDAyOGNlOTg4ZThjNDVkYTRmMmE2ZjgyNGQ0MjA0M2VhZTFiYzdhZTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HFnFTE6b4ge0Rd7ERe3nViz31hH9kFKce_m9fwtvUm0) ![image](https://private-user-images.githubusercontent.com/43116646/301376822-45af8b6b-2579-49d6-8db5-865181173b35.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzQ3MDIsIm5iZiI6MTcwNjgzNDQwMiwicGF0aCI6Ii80MzExNjY0Ni8zMDEzNzY4MjItNDVhZjhiNmItMjU3OS00OWQ2LThkYjUtODY1MTgxMTczYjM1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwMDQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTA0ZjhmN2I4NGM4MmZkMTQzOGQ1ZThlMzZhNmI3MzE1ZDFjYWFlMDk0MWMwNjMwYjQzMDQxNTY3ZGVmNzBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AgoHqHV1bLwKBaXSqvEFduf3xN3t9qnAVuUbZMSCYNU)

试一下最新版，刚刚更新了，跟我博客代码同步了。

**Comment by chakhsu** [comment]
> 试过删掉这些后加的，也没法恢复高亮

试一下最新版，刚刚更新了，跟我博客代码同步了。

**Comment by tom-kst** [comment]
> > 试过删掉这些后加的，也没法恢复高亮
> 
> 试一下最新版，刚刚更新了，跟我博客代码同步了。

哈哈哈~已经同步更新了，代码高亮回来了！感谢老大更新！
