### ISSUE TITLE
主题未兼容PHP8.3.3

### ISSUE THREAD

**Issue by callng** [chakhsu/pinghsu#59]
RT，启用主题后访问 显示Server Error 500错误

**Comment by chakhsu** [comment]
能不能提一个 pr，我这边没有这么高版本的php环境

**Comment by Asahina1096** [comment]
我测试过没有问题，跑的是php8.3.4

**Comment by callng** [comment]
> 我测试过没有问题，跑的是php8.3.4

好的，那这个我先关闭了。
