### ISSUE TITLE
为高亮代码增加$this->is('post')判断

### ISSUE THREAD

**Issue by heiybb** [chakhsu/pinghsu#6]
毕竟一般来说只有文章页需要使用代码高亮，通过增加判断来选择是否加载highlight.js可以稍微加快首页的打开速度
并且有pjax的优势，对文章内容的高亮显示速度应该影响甚小

**Comment by chakhsu** [comment]
加了这个判断，会造成首次访问有代码的文章页会无法高亮，我已经调试过这些js了。

**Comment by heiybb** [comment]
首次访问是指从首页点入文章页么，我认为是pjax的锅啊=-=
目前我这样处理
https://github.com/heiybb/pinghsu/blob/blog/footer.php#L244
没有出现无法高亮的情况

**Comment by chakhsu** [comment]
这个方法对instantclick的3.0.1版本无效。

**Comment by heiybb** [comment]
发现问题了，有点掉进黑洞的感觉。javascript战5渣表示很无奈。
